server:
  port: 8160 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-ucenter # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.236.154:8848 # nacos服务地址
  #spring:
  redis:
    host: 39.108.236.154
    port: 6379
    database: 0
    password:
    timeout: 30s
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.236.154:3306/guli_ucenter?serverTimezone=GMT%2B8
    username: guli_ucenter
    password: 123456
    hikari:
      max-lifetime: 40000
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:com/kenneth/guli/service/ucenter/mapper/xml/*.xml