server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.236.154:8848 # nacos服务地址
        ip: 192.168.10.30

aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    keyid: LTAI4G6HnxQarT5BAeYZNisN
    keysecret: Ud1CtBTjny5qn2kNq2J0hYC9MBDLz4
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: guli-file-kenneth